name: Metrics
on:
  schedule: [{cron: "0 */1 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}

          user: M-DinhHoangViet
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_lines: yes
