name: Metrics
on:
  schedule: [{cron: "20 */09 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.TOKEN }}
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_display: large
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, lines, percentage
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_notable: yes
          plugin_calendar: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_discussions: yes
          plugin_languages_threshold: 0%
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_people: yes
          plugin_people_types: contributors, stargazers, watchers, followers
          config_timezone: Asia/Ho_Chi_Minh
          plugin_followup: yes
          plugin_followup_sections: repositories, user
  
  github-3d-contrib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          date > generated.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A .
          git commit -m "Update profile-3d-contrib"
          git push
