name: Metrics
on:
  schedule: [{cron: "14 */03 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}

          user: M-DinhHoangViet
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_lines: yes
      
      - name: Last chess game from lichess.org
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.chess.svg
          token: NOT_NEEDED
          base: ""
          plugin_chess: yes
          plugin_chess_token: ${{ secrets.CHESS_TOKEN }}
          plugin_chess_platform: lichess.org
