# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: [{cron: "0 */1 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: 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

          user: M-DinhHoangViet
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Calcutta
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_lines: yes
