name: Metrics
on:
  schedule: [{cron: "14 */03 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      
      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.TOKEN }}
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          plugin_isocalendar: yes
          plugin_calendar: yes
          plugin_calendar_limit: 0
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 0
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_notable: yes
          plugin_discussions: yes
          plugin_discussions_categories_limit: 0
          config_timezone: Asia/Ho_Chi_Minh
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_lines: yes
